### ISSUE TITLE
Toggle or show parameter TYPE hint

### ISSUE THREAD

**Issue by amaisano** [robertgr991/php-parameter-hint#4]
I love seeing the variable names, but it would be even better to see the parameter TYPES printed out. PHPStorm has this feature:

```php
/**
  * @param \Namespace\AccountInterface $account
  * @param string $username
  */
public function my_fun(AccountInterface $account, string $username) {...}

return my_fun({AccountInterface $account:} $theAccount, {string $username:} 'amaisano');
```

(the {brackets} illustrate the auto-inserted hints).

**Comment by robertgr991** [comment]
Hello,

I think this can done with a toggle command so the regexp will also capture the type of parameters from the signature. I will take a look at this these days when I have some time.

**Comment by amaisano** [comment]
Great! Can we make it optional?

- Hints off
- Parameter name only
- parameter type only
- Parameter name + type

**Comment by robertgr991** [comment]
@amaisano This was included in the last version. There is a new commant CTRL + K T, you can doggle between 'disable' - show only name, 'type and name' and 'type', the hints off command it's still CTRL + K H and it takes priority over these. Let me know how this works for you.

**Comment by amaisano** [comment]
Thanks! I tested. Please take a look at the below issues and screenshot. The hints you see are defined in `__construct` above.

1. Not showing "string" for "id"
2. Showing question mark for some param types before the classname
3. Can we use the "short" name? Using the full namespace is too much space I think (most people would agree)
4. Hovering on the {type name: } combo decoration should show a hover box. It does not. Just "name" however still shows hover.

![image](https://user-images.githubusercontent.com/688435/88584816-40a04e80-d020-11ea-9a33-d424978f9912.png)

**Comment by robertgr991** [comment]
Thanks for the screenshot.

1. Does the `id` param have the type explicitly set? Like the params in the constructor from your ss, because the extension uses signature help provider to extract the hints, which seems to not show the type if not explicitly set so maybe this is the cause.
2. Don't really know right know what's with that random question mark, will look further.
3. Agreed, I made a change that takes the short name, will push it tomorrow after I test it more.
4. Can you provide a screenshot with this hover? Are you referring to the helper hover provided by intelephense extension? The hover still works for me as usual.

Nice theme btw

**Comment by amaisano** [comment]
1. ![image](https://user-images.githubusercontent.com/688435/88592549-2ec4a880-d02c-11ea-9270-bdc8edc94371.png)
2. It might be fore optional arguments (`?AccountInterface` means `function (...AccountInterface = NULL)`).
3. Without a leading slash :)
4. Nevermind - the hover I get is associated with the function/method call, not the decorator.

**Comment by robertgr991** [comment]
1. The signature provider returns the exact signature of the function so any type set with phpdoc won't show there, to take the type from there I have to use the hover provider which right now is used as a fallback to the first one because it's slower, I might change it to use it when either type and name or type is ON in order to take the types from phpdoc. Is the `string` type also set in the method signature or only in phpdoc?
2. I think you are right.
3. Yes, only the type without any extra chars.

**Comment by DominicVonk** [comment]
Hi I refactored the way when using the executeSignatureHelpProvider, to also provide the right typings

**Comment by amaisano** [comment]
Beautiful:

![image](https://user-images.githubusercontent.com/688435/88834806-5b023580-d1a2-11ea-9432-af2cb57884e3.png)

1. string was only hinted in the phpDoc, so I understand it will not appear in the decoration. That's fine. Usually these are self explanatory, and I don't think it's worth slowing things down to use the phpDoc instead.

Thank you for your work!

**Comment by robertgr991** [comment]
@amaisano I will release a new version later with some changes made by @DominicVonk and the types will also be taken from the doc provided by the signature help provider.

**Comment by robertgr991** [comment]
@amaisano Last version is published, when you have some time, please tell me how does it work for you, thx.

**Comment by amaisano** [comment]
Something odd with this:

![image](https://user-images.githubusercontent.com/688435/88887513-86206f80-d20a-11ea-93fd-7905bde4bdd5.png)

I'm not seeing the parameter name, "$key" -- I have both name + type enabled in settings.

**Comment by amaisano** [comment]
Beautiful! So it's picking up from phpDoc now? The "string|array" is not in the function signature:

![image](https://user-images.githubusercontent.com/688435/88887615-b7993b00-d20a-11ea-8bb6-ad02b9b953b6.png)

**Comment by robertgr991** [comment]
Yes, if it's available, it's taking it from the doc.

**Comment by amaisano** [comment]
I thought there were performance concerns about using phpDoc

**Comment by robertgr991** [comment]
There are performance concers with the hover provider, but @DominicVonk  pointed it out that the signature provider also provides the doc for each paramater, so now it parses the doc provided by siganture provider which has the same performance as before.

**Comment by amaisano** [comment]
Should we have an option to collapse the type and name (when both are shown), if they are equal? Like {string string}?

![image](https://user-images.githubusercontent.com/688435/89077063-6777c100-d34f-11ea-9240-37a6eecb5b03.png)

Alternatively, maybe show the name with a `$` in front of it to help visually clarify that it is a name, not a type? Like {string $string}.

**Comment by robertgr991** [comment]
Either of these would be easy to implement, so what do you think it's the better idea?
I may go with adding another option for collapsing type and name when equal, but the second option it's also fine, the advantage of the first one is that you save some space and you don't lose any information because you know the type from the name. This will apply only when they are equal so {UserServiceInterface userService} won't collapse.

Does the last version of the ext work as expected for you?

**Comment by amaisano** [comment]
Can we do both? Then it's always clear what the type is and what the $name is.

It works as expected! I noticed one small thing: when name == var is set to collapse, there is 1 empty space where the name would usually go:

![image](https://user-images.githubusercontent.com/688435/89080934-3d76cc80-d358-11ea-81ab-f7d7addc7953.png)

`FormStateInterface :` should be `FormStateInterface:`, right? Or is this intentional?

**Comment by robertgr991** [comment]
Yes, can do both. It's not intentional, I think I missed a trim somewhere.

**Comment by robertgr991** [comment]
@amaisano I published a new version with these changes and some more. Let me know when you can update it to tell me how it works.

**Comment by amaisano** [comment]
I'm still not able to see the `$` symbol in front of variable names. Is this a new setting I need to enable?

![image](https://user-images.githubusercontent.com/688435/90321148-0508ee00-df15-11ea-9dbf-60d5cce94088.png)

**Comment by robertgr991** [comment]
Right now the `$` shows only when the type is equal to the parameter name, but the next version will have a command to toggle this explicitly for every parameter name.

**Comment by amaisano** [comment]
Ah - ok! Looking forward to that update. Confirmed worked as designed for the current release:

![image](https://user-images.githubusercontent.com/688435/90407718-d013ad00-e074-11ea-8aa1-5a46899ef119.png)

**Comment by robertgr991** [comment]
@amaisano Can this be closed? Is everything working fine?

**Comment by amaisano** [comment]
Yes! Thanks for your work.

**Comment by robertgr991** [comment]
If you have other issues/suggestions, open a new issue, thanks.
